### ISSUE TITLE
Sloppy usage of paths

### ISSUE THREAD

**Issue by anuyts** [AndrewAtLarge/WebQuiz#12]
When you run `webquiz` on a file that is not in the current folder, e.g. `webquiz subfolder/myquiz.tex`, then some garbage is created in the _current_ folder (i.e. not in `subfolder`).

**Comment by AndrewAtLarge** [comment]
This is the way that LaTeX works: if you compile a file in a subdirectory from the parent directory then the PDF and log files appear in the parent.
