### ISSUE TITLE
duplicate of pgfsys-dvisvgm4ht.def in the package

### ISSUE THREAD

**Issue by u-fischer** [AndrewAtLarge/WebQuiz#17]
webquiz distributes a pgf driver with the name  `pgfsys-dvisvgm4ht.def `. This means that there are two version in texlive , and the webquiz one shadows the pgf driver and also local drivers installed in tex/generic.

Please remove or rename this duplicate. Packages shouldn't create such file name conflicts.  

(The wrong driver actually broke a svg create by make4ht as the local driver wasn't found anymore)

**Comment by AndrewAtLarge** [comment]
The driver files have already been removed from the WebQuiz so as soon as I update it on ctan this will be addressed. Unfortunafely I am flat out with other things at the moment so I am not sure when I will have time to finalise the update. Ultimately the problem with this driver was the result of the PGF team not fixing previous problems with their driver even though they had been alerted to them. This was the only reason why the driver was included with WebQuiz.

**Comment by u-fischer** [comment]
I understand that it is a problem if the default driver is not updated or fixed (or even created, I actually don't know if yours were first). But creating a duplicate or files in the "namespace" of another package isn't a good workaround. It is better in such cases to use another name, e.g. webquiz-pdfsys-dvisvgm4ht.def.

**Comment by AndrewAtLarge** [comment]
I have spoken with Karl Berry and the file has been taken out of TL. I will update the version on ctan soon.
