### ISSUE TITLE
WebQuiz error:   unrecognised file extension .ltx

### ISSUE THREAD

**Issue by pablgonz** [AndrewAtLarge/WebQuiz#5]
Hi, when I try to compile the documentation examples using the `.ltx` extension I get the error message:

```
----------------------------------------
WebQuiz error:
  unrecognised file extension .ltx
----------------------------------------
```

Thank you for your great work

**Comment by AndrewAtLarge** [comment]
The `.ltx` extension is used for latex system files. Webquiz expects LaTeX files with the standard `.tex` extension.
